import type React from 'react'
import {
    AndhrapradeshMap,
    ArunachalpradeshMap,
    AssamMap,
    BiharMap,
    ChhattisgarhMap,
    GoaMap,
    GujaratMap,
    HaryanaMap,
    HimachalpradeshMap,
    JharkhandMap,
    KarnatakaMap,
    KashmirMap,
    KeralaMap,
    LadakhMap,
    MadhyapradeshMap,
    MaharashtraMap,
    ManipurMap,
    MeghalayaMap,
    MizoramMap,
    NagalandMap,
    OdishaMap,
    PunjabMap,
    RajasthanMap,
    SikkimMap,
    TamilnaduMap,
    TelanganaMap,
    TripuraMap,
    UttarakhandMap,
    UttarpradeshMap,
    WestbengalMap,
    AndhrapradeshDistrictNames,
    ArunachalpradeshDistrictNames,
    AssamDistrictNames,
    BiharDistrictNames,
    ChhattisgarhDistrictNames,
    GoaDistrictNames,
    GujaratDistrictNames,
    HaryanaDistrictNames,
    HimachalpradeshDistrictNames,
    JharkhandDistrictNames,
    KarnatakaDistrictNames,
    KashmirDistrictNames,
    KeralaDistrictNames,
    LadakhDistrictNames,
    MadhyapradeshDistrictNames,
    MaharashtraDistrictNames,
    ManipurDistrictNames,
    MeghalayaDistrictNames,
    MizoramDistrictNames,
    NagalandDistrictNames,
    OdishaDistrictNames,
    PunjabDistrictNames,
    RajasthanDistrictNames,
    SikkimDistrictNames,
    TamilnaduDistrictNames,
    TelanganaDistrictNames,
    TripuraDistrictNames,
    UttarakhandDistrictNames,
    UttarpradeshDistrictNames,
    WestbengalDistrictNames,
} from 'svgmap-india'

export type MapProps = {
    className?: string
    size?: string
    mapColor?: string
    strokeColor?: string
    strokeWidth?: string
    hoverColor?: string
}

export type MapItem = {
    id: string
    label: string
    componentName: string
    Map: React.ComponentType<{ onClick: (value: string) => void } & MapProps>
    districtNames: Record<string, string>
}

export const MAPS: MapItem[] = [
    {
        id: 'andhrapradesh',
        label: 'Andhrapradesh',
        componentName: 'Andhrapradesh',
        Map: AndhrapradeshMap,
        districtNames: AndhrapradeshDistrictNames,
    },
    {
        id: 'arunachalpradesh',
        label: 'Arunachalpradesh',
        componentName: 'Arunachalpradesh',
        Map: ArunachalpradeshMap,
        districtNames: ArunachalpradeshDistrictNames,
    },
    {
        id: 'assam',
        label: 'Assam',
        componentName: 'Assam',
        Map: AssamMap,
        districtNames: AssamDistrictNames,
    },
    {
        id: 'bihar',
        label: 'Bihar',
        componentName: 'Bihar',
        Map: BiharMap,
        districtNames: BiharDistrictNames,
    },
    {
        id: 'chhattisgarh',
        label: 'Chhattisgarh',
        componentName: 'Chhattisgarh',
        Map: ChhattisgarhMap,
        districtNames: ChhattisgarhDistrictNames,
    },
    {
        id: 'goa',
        label: 'Goa',
        componentName: 'Goa',
        Map: GoaMap,
        districtNames: GoaDistrictNames,
    },
    {
        id: 'gujarat',
        label: 'Gujarat',
        componentName: 'Gujarat',
        Map: GujaratMap,
        districtNames: GujaratDistrictNames,
    },
    {
        id: 'haryana',
        label: 'Haryana',
        componentName: 'Haryana',
        Map: HaryanaMap,
        districtNames: HaryanaDistrictNames,
    },
    {
        id: 'himachalpradesh',
        label: 'Himachalpradesh',
        componentName: 'Himachalpradesh',
        Map: HimachalpradeshMap,
        districtNames: HimachalpradeshDistrictNames,
    },
    {
        id: 'jharkhand',
        label: 'Jharkhand',
        componentName: 'Jharkhand',
        Map: JharkhandMap,
        districtNames: JharkhandDistrictNames,
    },
    {
        id: 'karnataka',
        label: 'Karnataka',
        componentName: 'Karnataka',
        Map: KarnatakaMap,
        districtNames: KarnatakaDistrictNames,
    },
    {
        id: 'kashmir',
        label: 'Kashmir',
        componentName: 'Kashmir',
        Map: KashmirMap,
        districtNames: KashmirDistrictNames,
    },
    {
        id: 'kerala',
        label: 'Kerala',
        componentName: 'Kerala',
        Map: KeralaMap,
        districtNames: KeralaDistrictNames,
    },
    {
        id: 'ladakh',
        label: 'Ladakh',
        componentName: 'Ladakh',
        Map: LadakhMap,
        districtNames: LadakhDistrictNames,
    },
    {
        id: 'madhyapradesh',
        label: 'Madhyapradesh',
        componentName: 'Madhyapradesh',
        Map: MadhyapradeshMap,
        districtNames: MadhyapradeshDistrictNames,
    },
    {
        id: 'maharashtra',
        label: 'Maharashtra',
        componentName: 'Maharashtra',
        Map: MaharashtraMap,
        districtNames: MaharashtraDistrictNames,
    },
    {
        id: 'manipur',
        label: 'Manipur',
        componentName: 'Manipur',
        Map: ManipurMap,
        districtNames: ManipurDistrictNames,
    },
    {
        id: 'meghalaya',
        label: 'Meghalaya',
        componentName: 'Meghalaya',
        Map: MeghalayaMap,
        districtNames: MeghalayaDistrictNames,
    },
    {
        id: 'mizoram',
        label: 'Mizoram',
        componentName: 'Mizoram',
        Map: MizoramMap,
        districtNames: MizoramDistrictNames,
    },
    {
        id: 'nagaland',
        label: 'Nagaland',
        componentName: 'Nagaland',
        Map: NagalandMap,
        districtNames: NagalandDistrictNames,
    },
    {
        id: 'odisha',
        label: 'Odisha',
        componentName: 'Odisha',
        Map: OdishaMap,
        districtNames: OdishaDistrictNames,
    },
    {
        id: 'punjab',
        label: 'Punjab',
        componentName: 'Punjab',
        Map: PunjabMap,
        districtNames: PunjabDistrictNames,
    },
    {
        id: 'rajasthan',
        label: 'Rajasthan',
        componentName: 'Rajasthan',
        Map: RajasthanMap,
        districtNames: RajasthanDistrictNames,
    },
    {
        id: 'sikkim',
        label: 'Sikkim',
        componentName: 'Sikkim',
        Map: SikkimMap,
        districtNames: SikkimDistrictNames,
    },
    {
        id: 'tamilnadu',
        label: 'Tamilnadu',
        componentName: 'Tamilnadu',
        Map: TamilnaduMap,
        districtNames: TamilnaduDistrictNames,
    },
    {
        id: 'telangana',
        label: 'Telangana',
        componentName: 'Telangana',
        Map: TelanganaMap,
        districtNames: TelanganaDistrictNames,
    },
    {
        id: 'tripura',
        label: 'Tripura',
        componentName: 'Tripura',
        Map: TripuraMap,
        districtNames: TripuraDistrictNames,
    },
    {
        id: 'uttarakhand',
        label: 'Uttarakhand',
        componentName: 'Uttarakhand',
        Map: UttarakhandMap,
        districtNames: UttarakhandDistrictNames,
    },
    {
        id: 'uttarpradesh',
        label: 'Uttarpradesh',
        componentName: 'Uttarpradesh',
        Map: UttarpradeshMap,
        districtNames: UttarpradeshDistrictNames,
    },
    {
        id: 'westbengal',
        label: 'Westbengal',
        componentName: 'Westbengal',
        Map: WestbengalMap,
        districtNames: WestbengalDistrictNames,
    },
]

export const DARK_DEFAULTS = {
    size: '500px',
    mapColor: '#1f2530',
    strokeColor: '#e9edf3',
    strokeWidth: '1',
    hoverColor: '#e6eaef',
}

export const LIGHT_DEFAULTS = {
    size: '500px',
    mapColor: '#ffffff',
    strokeColor: '#111111',
    strokeWidth: '1',
    hoverColor: '#3b3f46',
}
